.\" Manpage for procdump.
.TH man 8 "11/30/2017" "1.0" "procdump manpage"
.SH NAME
procdump \- generate coredumps based of performance triggers.
.SH SYNOPSIS
procdump [OPTIONS...] TARGET
      -C   CPU threshold at which to create a coredump of the process from 0 to 200
      -c   CPU threshold below which to create a coredump of the process from 0 to 200
      -M   Memory commit threshold in MB at which to create a coredump
      -m   Trigger when memory commit drops below specified MB value
      -n   Number of dumps to write before exiting
      -s   Consecutive seconds before dump is written (default is 10)
  TARGET must be exactly one of these:
      -p   pid of the process
.SH DESCRIPTION
procdump is a Linux reimagining of the class ProcDump tool from the Sysinternals suite of tools for Windows. Procdump provides a convenient way for Linux developers to create core dumps of their application based on performance triggers.

