parameters:
- name: srcPath
  type: string
  default: '.'
- name: runStaticAnalysis
  type: boolean
  default: False
- name: builddir
  type: string
  default: 'procdump_build'    

steps:
- script: |
    mkdir -p ${{ parameters.srcPath }}/${{ parameters.builddir }} && cd ${{ parameters.srcPath }}/${{ parameters.builddir }}
    cmake ..
    make
  displayName: "Build ProcDump binaries"
