parameters:
- name: ccopts
  type: string
  default: ''
- name: extra
  type: string
  default: ''

steps:
- script: |
    mkdir procdump_build && cd procdump_build
    cmake ..
    make
  displayName: "Build ProcDump binaries"
