parameters:
- name: srcPath
  type: string
  default: '.'
- name: runStaticAnalysis
  type: boolean
  default: False

steps:
- script: |
    echo "Version = $(VERSION)"
    cd ${{ parameters.srcPath }}
    mkdir procdump_build && cd procdump_build
    cmake ..
    make
  displayName: "Build ProcDump binaries"
