parameters:
- name: srcPath
  type: string
  default: '.'

steps:
- script: |
    cd ${{ parameters.srcPath }}
    mkdir procdump_build && cd procdump_build
    cmake ..
    make
  displayName: "Build ProcDump binaries"
